server:
  port: 8480
spring:
  application:
    name: stock-service
  kafka:
    topic:
      name: order-topic
    consumer:
      bootstrap-servers: localhost:9092
      group-id: stock-api
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

  datasource:
    url: jdbc:h2:mem:mydb;
#    url: jdbc:h2:file:./H2DBFiles/UserProfileDatabase
    username: user
    password:
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console